name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: csapp-docker
      run: docker build . --tag xieguochao/csapp:${{  github.ref_name }}
      
    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: xieguochao
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Push Docker image
      run: docker push xieguochao/csapp:${{  github.ref_name }}
